### PR TITLE
Added smps-spec contributing doc

### LINKED ISSUE #68: [Docs] Create contributing docs for the smps-spec.io site
**Current State:**
Site is created by Jekyll.
Site runs on GitHub Pages.
Site sits in this repo under /docs.

**Desired State:**
Contributing docs are needed here. The same docs used for either layer5.io or meshery.io can be copied.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by PluckyPrecious**
Signed-off-by: PluckyPrecious <prekel27@gmail.com>

**Description**
Created Doc README.md, CONTRIBUTING-gitflow.md file and some edits in the CONTRIBUTING.md

This PR fixes #68

**Notes for Reviewers**
@leecalcote please check this out.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by PluckyPrecious** [comment]
Thanks @leecalcote it’s a pleasure. 🙏🏽

**Comment by chandrashritii** [comment]
Merging. Good work @PluckyPrecious

**Comment by leecalcote** [comment]
Whee! 😄

**Comment by PluckyPrecious** [comment]
> Merging. Good work @PluckyPrecious

Thanks @chandrashritii 🎉

**Pull request merged**
