### PR TITLE
example files

### LINKED ISSUE #2: Add sample client-side test result
The client-side test result should contain throughput, errors, latency and so on from a performance test.

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

fixes #2

### CODE REVIEW

**Comment by mcastre** [comment]
Hey everyone! I keep getting bombarded by emails from github for every pr made by the organization. I tried removing myself from the organization and stopped watching repos but I’m still getting emails. Could you see if I’m listed somewhere and remove me please? Thanks!

**Comment by leecalcote** [comment]
Hi @mcastre, broadly, it sounds like you'll be unsubscribed. Two instances come to mind in which you'll get notifications:

- unwatch this repo - https://github.com/layer5io/service-mesh-performance-specification/watchers
- there are specific issues that your user has been listed on or has had activity on and so GH sends you notifications on those specific ones. I think there are only a couple of those left.

**Comment by mcastre** [comment]
Hey Lee! Yea maybe I need to manually unwatch repos

**Comment by leecalcote** [comment]
Thank you, gents. 

@mcastre unwanted notifications are a nuisance. Meshery is seeing a big uptick in interest. Please know that you’re always welcome in the community - come and go as you will. 👍  Thank you for the impact that you have already made.

**Pull request merged**
